//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BeyondThemes.BeyondAdmin.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Course
    {
        public Course()
        {
            this.Course_Registration = new HashSet<Course_Registration>();
            this.Feedbacks = new HashSet<Feedback>();
        }
    
        public int Course_ID { get; set; }
        public string Course_Type { get; set; }
        public string Course_Desc { get; set; }
        public Nullable<int> Teacher_ID { get; set; }
        public Nullable<int> Course_Max_Size { get; set; }
        public Nullable<System.DateTime> Course_Start_Date { get; set; }
        public Nullable<System.DateTime> Course_End_Date { get; set; }
        public Nullable<System.TimeSpan> Course_Time_Start { get; set; }
        public Nullable<System.TimeSpan> Course_Time_End { get; set; }
        public Nullable<float> Course_Cost { get; set; }
        public string Course_Location { get; set; }
        public string Course_Notes { get; set; }
    
        public virtual ICollection<Course_Registration> Course_Registration { get; set; }
        public virtual ICollection<Feedback> Feedbacks { get; set; }
        public virtual Teacher Teacher { get; set; }
    }
}
